// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxkecfeosxodicpocvzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4a2VjZmVvc3hvZGljcG9jdnpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1MDA2MTcsImV4cCI6MjA5NjA3NjYxN30.Q_EBJBNDHssk-jaRD9b7WEkzqXjT65wylTp2XaKx_hI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});